Smoke test

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -425,20 +425,33 @@ jobs:
           name: Backend smoke test.
           command: |
             # your code here
-            BACKEND_PUBLIC_IP=$(aws ec2 describe-instances \
-             --filters Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7} \
-             --query 'Reservations[*].Instances[*].PublicIpAddress' \
-             --output text)       
-            export API_URL=http://${BACKEND_PUBLIC_IP}:3030
-            echo ${BACKEND_PUBLIC_IP}
-            echo backend-${CIRCLE_WORKFLOW_ID:0:7}
-            echo ${ API_URL}
-            if curl -s ${API_URL}/api/status | grep "ok"
+            export BACKEND_IP=$(aws ec2 describe-instances \
+            --query 'Reservations[*].Instances[*].PublicIpAddress' \
+            --filters Name=tag:aws:cloudformation:stack-name,Values=udapeople-backend-${CIRCLE_WORKFLOW_ID:0:7} \
+            --output text)
+            export API_URL="http://${BACKEND_IP}:3030"
+            echo "${API_URL}"
+            if curl -s "${API_URL}/api/status" | grep "ok"
             then
-              exit 0
+                return 0
             else
-              exit 1
+                return 1
             fi
+
+            # BACKEND_PUBLIC_IP=$(aws ec2 describe-instances \
+            #  --filters Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7} \
+            #  --query 'Reservations[*].Instances[*].PublicIpAddress' \
+            #  --output text)       
+            # export API_URL=http://${BACKEND_PUBLIC_IP}:3030
+            # echo ${BACKEND_PUBLIC_IP}
+            # echo backend-${CIRCLE_WORKFLOW_ID:0:7}
+            # echo ${API_URL}
+            # if curl -s ${API_URL}/api/status | grep "ok"
+            # then
+            #   exit 0
+            # else
+            #   exit 1
+            # fi
 
       - run:
           name: Frontend smoke test.
@@ -485,24 +498,37 @@ jobs:
       - revert-migrations    
    # Here's where you will add some code to rollback on failure  
 
-  # # cleanup:
-  #   docker:
-  #     # Docker image here
-  #   steps:
-  #     # Checkout code from git
-  #     - run:
-  #         name: Get old stack workflow id
-  #         command: |
-  #           # your code here
-  #           export OldWorkflowID="the id here"
-  #           export STACKS=[] #put the list of stacks here
-  #     - run:
-  #         name: Remove old stacks and files
-  #         command: |
-  #           if [[ "${STACKS[@]}" =~ "${OldWorkflowID}" ]]
-  #           then
-  #             # your code here
-  #           fi
+  # cleanup:
+    docker:
+      # Docker image here
+       - image: cimg/base:stable
+    steps:
+      # Checkout code from git
+      - checkout
+      - install_awscli       
+      - run:
+          name: Get old stack workflow id
+          command: |
+            # your code here
+              export STACKS=($(aws cloudformation list-stacks  \
+              --query "StackSummaries[*].StackName" \
+              --stack-status-filter CREATE_COMPLETE --no-paginate --output text))         
+              echo Stack names: "${STACKS[@]}"  
+              export OldWorkflowID=$(curl --insecure https://kvdb.io/L8WY5ToZYZNmcgdX74bWAK/workflowid)
+              echo OldWorkflowID: $OldWorkflowID
+                     
+      - run:
+          name: Remove old stacks and files
+          command: |
+            export OldWorkflowID=$(curl --insecure https://kvdb.io/L8WY5ToZYZNmcgdX74bWAK/workflowid)
+            echo Old Workflow ID: $OldWorkflowID
+
+            if [["${STACKS[@]}"  == "$OldWorkflowID" ]]          
+            then
+             aws s3 rm "s3://udapeople-${OldWorkflowID}" --recursive
+             aws cloudformation delete-stack --stack-name "udapeople-backend-${OldWorkflowID}"
+             aws cloudformation delete-stack --stack-name "udapeople-frontend-${OldWorkflowID}"
+            fi
             
 
 workflows:
@@ -536,5 +562,5 @@ workflows:
           requires: [deploy-backend, deploy-frontend]
       - cloudfront-update:
           requires: [smoke-test]
-      # - cleanup:
-      #     requires: [cloudfront-update]
+      - cleanup:
+          requires: [cloudfront-update]
